name: Build

on:
  push

jobs:
  create-release:
    name: Build and Create Tagged release
    runs-on: ubuntu-latest

    steps:
      - name: Install archive tools
        run: sudo apt install zip

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      - name: Install dependencies
        run: cd web && yarn

      - name: Run build
        run: |
          cd web
          yarn add @mantine/core @mantine/hooks @mantine/notifications @mantine/nprogress @mantine/modals @mantine/carousel embla-carousel-react @mantine/spotlight @mantine/form @mantine/dates dayjs
          yarn add --dev postcss postcss-preset-mantine postcss-simple-vars
          yarn run build

      - name: Bundle files
        run: |
          mkdir -p ./temp/vHud
          mkdir -p ./temp/vHud/web/
          cp ./{LICENSE,README.md,fxmanifest.lua} ./temp/vHud
          cp -r ./shared ./temp/vHud
          cp -r ./client ./temp/vHud
          cp -r ./server ./temp/vHud
          cp -r ./web/build ./temp/vHud/web/
          cd ./temp && zip -r ../vHud.zip ./vHud

      - name: Update tag ref
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -f ${{ github.sha }} -m "Updated tag reference"
          git push origin ${{ github.sha }} --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        id: auto_release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Testing.'
          prerelease: false
          files: vHud.zip

        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
