on: push
jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd web
          yarn  # Use npm install if you prefer npm
          yarn add @mantine/core @mantine/hooks @mantine/notifications @mantine/nprogress @mantine/modals @mantine/carousel embla-carousel-react @mantine/spotlight @mantine/form @mantine/dates dayjs

      - name: Build UI
        run: |
          cd web
          yarn run build  # Use npm run build if you prefer npm

  release:
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.run_number }}
          release_name: ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        env: GITHUB_TOKEN ${{ secrets.GITHUB_TOKEN }}

        with:
          name: release-artifact
          path: web/build # Update this path based on your actual build output directory

